version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/Istanbul
    open-pull-requests-limit: 5
    reviewers:
      - umudique
    labels:
      - dependencies
    groups:
      non-security-updates:
        dependency-type: production
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/Istanbul
    open-pull-requests-limit: 3
    reviewers:
      - umudique
    labels:
      - dependencies
      - ci
